//! Regeneration of the vendored per-model request-facts snapshot.
//!
//! The snapshot committed to the repository is the runtime source of truth, so
//! it must be regenerated by the same projection the runtime loads rather than
//! by an out-of-band script. This module fetches the upstream catalog and
//! projects it; writing and comparison stay in the CLI, which owns file paths.

use bytes::Bytes;
use http::{header, Method, Request, StatusCode, Uri};
use http_body_util::Full;
use hyper_rustls::HttpsConnectorBuilder;
use hyper_util::{client::legacy::Client, rt::TokioExecutor};
use pooler_http::collect_body_limited;
use pooler_model_catalog::{ModelFacts, ModelFactsError, MAX_UPSTREAM_CATALOG_BYTES};
use ring::digest::{digest, SHA256};
use thiserror::Error;

/// Fetch the upstream catalog over HTTPS and project the pinned snapshot.
pub async fn fetch_model_facts(url: &str) -> Result<ModelFacts, ModelFactsRefreshError> {
    let uri = url
        .parse::<Uri>()
        .map_err(|_| ModelFactsRefreshError::InvalidUrl)?;
    if uri.scheme_str() != Some("https") {
        return Err(ModelFactsRefreshError::InvalidUrl);
    }

    let connector = HttpsConnectorBuilder::new()
        .with_native_roots()
        .map_err(|_| ModelFactsRefreshError::TlsClient)?
        .https_only()
        .enable_http1()
        .enable_http2()
        .build();
    let client = Client::builder(TokioExecutor::new()).build::<_, Full<Bytes>>(connector);

    let mut request = Request::new(Full::new(Bytes::new()));
    *request.method_mut() = Method::GET;
    *request.uri_mut() = uri;
    request.headers_mut().insert(
        header::ACCEPT,
        http::HeaderValue::from_static("application/json"),
    );

    let response = client
        .request(request)
        .await
        .map_err(|_| ModelFactsRefreshError::Transport)?;
    let status = response.status();
    if !status.is_success() {
        return Err(ModelFactsRefreshError::UpstreamStatus { status });
    }
    let document = collect_body_limited(response.into_body(), MAX_UPSTREAM_CATALOG_BYTES)
        .await
        .map_err(|error| match error {
            pooler_http::BodyLimitError::TooLarge { .. } => ModelFactsRefreshError::TooLarge,
            _ => ModelFactsRefreshError::Transport,
        })?;
    project_model_facts(&document, url)
}

/// Project an already-obtained upstream catalog document.
///
/// The digest is computed here so the recorded provenance always describes the
/// exact bytes that produced the snapshot.
pub fn project_model_facts(
    document: &[u8],
    source_url: &str,
) -> Result<ModelFacts, ModelFactsRefreshError> {
    let source_sha256 = sha256_hex(document);
    ModelFacts::from_models_dev_catalog(document, source_url, &source_sha256)
        .map_err(ModelFactsRefreshError::Projection)
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hex = String::with_capacity(64);
    for byte in digest(&SHA256, bytes).as_ref() {
        hex.push_str(&format!("{byte:02x}"));
    }
    hex
}

/// Failure fetching or projecting the upstream model catalog.
#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum ModelFactsRefreshError {
    #[error("model catalog URL must be an absolute HTTPS URL")]
    InvalidUrl,
    #[error("model catalog TLS client could not be initialized")]
    TlsClient,
    #[error("model catalog could not be fetched")]
    Transport,
    #[error("model catalog request failed with status {status}")]
    UpstreamStatus { status: StatusCode },
    #[error("model catalog exceeds the {MAX_UPSTREAM_CATALOG_BYTES} byte bound")]
    TooLarge,
    #[error(transparent)]
    Projection(ModelFactsError),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn digests_are_lowercase_hexadecimal_sha256() {
        let digest = sha256_hex(b"pooler");
        assert_eq!(digest.len(), 64);
        assert!(digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)));
    }

    #[test]
    fn projection_records_the_digest_of_the_projected_document() {
        let document = br#"{"openai":{"models":{"m":{"temperature":false}}}}"#;
        let facts = project_model_facts(document, "https://models.dev/api.json")
            .expect("projection succeeds");

        assert_eq!(facts.source_sha256(), sha256_hex(document));
        assert_eq!(facts.entry_count(), 1);
    }

    #[tokio::test]
    async fn non_https_catalog_urls_are_rejected_before_any_request() {
        assert_eq!(
            fetch_model_facts("http://models.dev/api.json").await,
            Err(ModelFactsRefreshError::InvalidUrl)
        );
        assert_eq!(
            fetch_model_facts("models.dev/api.json").await,
            Err(ModelFactsRefreshError::InvalidUrl)
        );
    }
}
