//! JSON helpers that retain the original representation until a mutation is
//! requested.

use std::{borrow::Cow, fmt, str::FromStr};

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;
use thiserror::Error;

/// Errors produced by [`PreservedJson`].
#[derive(Debug, Error)]
pub enum PreservedJsonError {
    /// The input was not a complete JSON document.
    #[error("invalid JSON: {0}")]
    InvalidJson(#[from] serde_json::Error),
    /// A JSON pointer did not identify an existing value.
    #[error("JSON pointer `{pointer}` was not found")]
    PointerNotFound {
        /// Pointer that failed to resolve.
        pointer: String,
    },
    /// A JSON pointer selected a value of the wrong kind for the requested
    /// operation.
    #[error("JSON pointer `{pointer}` does not select an object or array")]
    NotContainer {
        /// Pointer that selected a scalar value.
        pointer: String,
    },
    /// Removing the root value would leave no JSON document.
    #[error("the root JSON value cannot be removed")]
    CannotRemoveRoot,
}

/// A JSON document that keeps its input bytes until the value is changed.
///
/// This type is useful on inspect and patch routes.  A decode/encode cycle can
/// therefore forward whitespace, object key order, and other harmless details
/// exactly as received.  Once a mutation is made, serialization is delegated
/// to `serde_json` and the original representation is no longer returned.
#[derive(Clone)]
pub struct PreservedJson {
    original: Vec<u8>,
    value: Value,
    modified: bool,
}

impl PreservedJson {
    /// Parses a complete JSON document and retains the supplied bytes.
    pub fn from_bytes(bytes: impl Into<Vec<u8>>) -> Result<Self, PreservedJsonError> {
        let original = bytes.into();
        let value = serde_json::from_slice(&original)?;
        Ok(Self {
            original,
            value,
            modified: false,
        })
    }

    /// Parses a UTF-8 JSON document and retains the supplied bytes.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(value: &str) -> Result<Self, PreservedJsonError> {
        Self::from_bytes(value.as_bytes().to_vec())
    }

    /// Creates a document from a decoded value.
    ///
    /// The generated bytes are considered the initial representation and will
    /// be returned unchanged until the value is mutated.
    pub fn from_value(value: Value) -> Result<Self, PreservedJsonError> {
        let original = serde_json::to_vec(&value)?;
        Ok(Self {
            original,
            value,
            modified: false,
        })
    }

    /// Returns the decoded value.
    #[must_use]
    pub const fn value(&self) -> &Value {
        &self.value
    }

    /// Returns the original input bytes, regardless of later mutations.
    #[must_use]
    pub fn original_bytes(&self) -> &[u8] {
        &self.original
    }

    /// Returns whether a mutation has invalidated the original byte form.
    #[must_use]
    pub const fn is_modified(&self) -> bool {
        self.modified
    }

    /// Returns the current representation without needlessly re-serializing an
    /// unmodified document.
    #[must_use]
    pub fn bytes(&self) -> Cow<'_, [u8]> {
        if self.modified {
            Cow::Owned(serde_json::to_vec(&self.value).expect("serde_json::Value is serializable"))
        } else {
            Cow::Borrowed(&self.original)
        }
    }

    /// Returns the current representation as owned bytes.
    #[must_use]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.bytes().into_owned()
    }

    /// Returns a value selected by an RFC 6901 JSON pointer.
    #[must_use]
    pub fn pointer(&self, pointer: &str) -> Option<&Value> {
        self.value.pointer(pointer)
    }

    /// Replaces an existing value selected by a JSON pointer.
    ///
    /// The empty pointer replaces the root.  For non-root pointers this method
    /// intentionally requires the target to exist; callers that need to create
    /// a new object member can use [`Self::insert`].
    pub fn set_pointer(
        &mut self,
        pointer: &str,
        value: Value,
    ) -> Result<Value, PreservedJsonError> {
        if pointer.is_empty() {
            self.modified = true;
            return Ok(std::mem::replace(&mut self.value, value));
        }
        let Some(target) = self.value.pointer_mut(pointer) else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: pointer.to_owned(),
            });
        };
        self.modified = true;
        Ok(std::mem::replace(target, value))
    }

    /// Alias for [`Self::set_pointer`] used by patch implementations.
    pub fn replace(&mut self, pointer: &str, value: Value) -> Result<Value, PreservedJsonError> {
        self.set_pointer(pointer, value)
    }

    /// Inserts or replaces an object member at a JSON pointer.
    ///
    /// The pointer must identify an existing object.  An empty pointer is not a
    /// valid parent for this operation.
    pub fn insert(
        &mut self,
        object_pointer: &str,
        key: impl Into<String>,
        value: Value,
    ) -> Result<Option<Value>, PreservedJsonError> {
        let key = key.into();
        let Some(parent) = self.value.pointer_mut(object_pointer) else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: object_pointer.to_owned(),
            });
        };
        let Value::Object(object) = parent else {
            return Err(PreservedJsonError::NotContainer {
                pointer: object_pointer.to_owned(),
            });
        };
        self.modified = true;
        Ok(object.insert(key, value))
    }

    /// Removes an existing value selected by a JSON pointer.
    pub fn remove(&mut self, pointer: &str) -> Result<Value, PreservedJsonError> {
        if pointer.is_empty() {
            return Err(PreservedJsonError::CannotRemoveRoot);
        }
        let Some((parent_pointer, token)) = split_pointer(pointer) else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: pointer.to_owned(),
            });
        };
        let Some(parent) = self.value.pointer_mut(parent_pointer) else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: parent_pointer.to_owned(),
            });
        };
        let Some(token) = decode_pointer_token(token) else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: pointer.to_owned(),
            });
        };
        let removed = match parent {
            Value::Object(object) => object.remove(&token),
            Value::Array(array) => token
                .parse::<usize>()
                .ok()
                .and_then(|index| (index < array.len()).then(|| array.remove(index))),
            Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => None,
        };
        let Some(removed) = removed else {
            return Err(PreservedJsonError::PointerNotFound {
                pointer: pointer.to_owned(),
            });
        };
        self.modified = true;
        Ok(removed)
    }

    /// Applies a bounded mutation and marks the representation as modified.
    pub fn edit<F>(&mut self, edit: F)
    where
        F: FnOnce(&mut Value),
    {
        edit(&mut self.value);
        self.modified = true;
    }
}

fn split_pointer(pointer: &str) -> Option<(&str, &str)> {
    let separator = pointer.rfind('/')?;
    let (parent, token) = pointer.split_at(separator);
    Some((if parent.is_empty() { "" } else { parent }, &token[1..]))
}

fn decode_pointer_token(token: &str) -> Option<String> {
    let mut decoded = String::with_capacity(token.len());
    let mut chars = token.chars();
    while let Some(character) = chars.next() {
        if character != '~' {
            decoded.push(character);
            continue;
        }
        match chars.next()? {
            '0' => decoded.push('~'),
            '1' => decoded.push('/'),
            _ => return None,
        }
    }
    Some(decoded)
}

impl PartialEq for PreservedJson {
    fn eq(&self, other: &Self) -> bool {
        self.original == other.original
            && self.value == other.value
            && self.modified == other.modified
    }
}

impl fmt::Debug for PreservedJson {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PreservedJson")
            .field("byte_len", &self.bytes().len())
            .field("modified", &self.modified)
            .finish()
    }
}

impl Serialize for PreservedJson {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        self.value.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for PreservedJson {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = Value::deserialize(deserializer)?;
        Self::from_value(value).map_err(serde::de::Error::custom)
    }
}

impl TryFrom<Vec<u8>> for PreservedJson {
    type Error = PreservedJsonError;

    fn try_from(value: Vec<u8>) -> Result<Self, Self::Error> {
        Self::from_bytes(value)
    }
}

impl TryFrom<&[u8]> for PreservedJson {
    type Error = PreservedJsonError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        Self::from_bytes(value.to_vec())
    }
}

impl TryFrom<&str> for PreservedJson {
    type Error = PreservedJsonError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::from_str(value)
    }
}

impl FromStr for PreservedJson {
    type Err = PreservedJsonError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_bytes(value.as_bytes().to_vec())
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{PreservedJson, PreservedJsonError};

    #[test]
    fn untouched_input_keeps_original_bytes() {
        let input = b"{ \"b\": 2, \"a\": [1, 2] }\n";
        let json = PreservedJson::from_bytes(input.to_vec()).expect("valid JSON");
        assert_eq!(json.bytes().as_ref(), input);
        assert_eq!(json.original_bytes(), input);
        assert!(!json.is_modified());
    }

    #[test]
    fn mutation_switches_to_serialized_value() {
        let mut json = PreservedJson::from_str("{\"value\":1}").expect("valid JSON");
        let previous = json
            .set_pointer("/value", json!(2))
            .expect("existing pointer");
        assert_eq!(previous, json!(1));
        assert_eq!(json.bytes().as_ref(), br#"{"value":2}"#);
        assert!(json.is_modified());
    }

    #[test]
    fn insert_and_remove_escape_pointer_tokens() {
        let mut json = PreservedJson::from_str("{\"a/b\":{}}").expect("valid JSON");
        json.insert("/a~1b", "~key", json!(true)).expect("object");
        assert_eq!(json.pointer("/a~1b/~0key"), Some(&json!(true)));
        let removed = json.remove("/a~1b/~0key").expect("existing value");
        assert_eq!(removed, json!(true));
    }

    #[test]
    fn scalar_insert_reports_container_error() {
        let mut json = PreservedJson::from_str("{\"value\":1}").expect("valid JSON");
        let error = json
            .insert("/value", "nested", json!(2))
            .expect_err("scalar");
        assert!(matches!(error, PreservedJsonError::NotContainer { .. }));
    }
}
